# Source: tektonpipelines/templates/tasks/owasp-dependencies-check.yml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: owasp-dependencies-check
  annotations:
    meta.helm.sh/release-name: 'tektonpipelines'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  description: |
    Checks the project depencencies with OWASP Dependency-Check and fails the build if issues are found.
  workspaces:
    - name: source
      description: sources dir
  params:
    - name: PROJECT_NAME
    - name: SDLC_PIPE_HELPER
    - name: ODC_IMAGE
      default: "owasp/dependency-check:7.1.0"
    - name: ODC_CACHE_PVC
      default: odc-cache
    - name: ODC_CVSS
      description: If the score set between 0 and 10 the exit code from dependency-check will indicate if a vulnerability with a CVSS score equal to or higher was identified.
      default: "7"
    - name: ODC_SUPPRESSION_FILE
      default: "odc-suppression.xml"
  stepTemplate:
    name: ""
  volumes:
    - name: $(params.ODC_CACHE_PVC)
      persistentVolumeClaim:
        claimName: odc-cache
  results:
    - name: odc-result
      description: dependency-check execution result
  steps:
    - name: odc-check
      image: $(params.ODC_IMAGE)
      workingDir: $(workspaces.source.path)
      onError: continue
      securityContext:
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -e
        
        create_dir_if_not_exist() {
          if [ ! -d "$1" ]; then
            echo "Initially creating persistent directory: $1"
            mkdir -p "$1"
          fi
        }

        ODC_DIR=/usr/share/dependency-check
        ODC_BIN_DIR="$ODC_DIR/bin"
        ODC_DATA_DIR="$ODC_DIR/data"
        ODC_CACHE_DIR="$ODC_DATA_DIR/cache"

        if test -f "$(params.ODC_SUPPRESSION_FILE)"; then
          SUPPRESSION="--suppression $(params.ODC_SUPPRESSION_FILE)"
        else
          SUPPRESSION=""
        fi

        create_dir_if_not_exist "$ODC_DATA_DIR"
        create_dir_if_not_exist "$ODC_CACHE_DIR"

        "$ODC_BIN_DIR"/dependency-check.sh --failOnCVSS "$(params.ODC_CVSS)" --scan ./ --format "SARIF" --project "$(params.PROJECT_NAME)" --out "." $SUPPRESSION
      volumeMounts:
        - name: $(params.ODC_CACHE_PVC)
          mountPath: /usr/share/dependency-check/data
    - name: owasp-publish-report
      image: "$(params.SDLC_PIPE_HELPER)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        source $(workspaces.source.path)/.jx/variables.sh

        sdlcpipelinehelper sarif-publish \
          --repoOwner="$(params.REPO_OWNER)"  --repoName="$(params.REPO_NAME)" --sourceRoot="$(workspaces.source.path)" --commit="$HEAD_COMMIT" \
          --detailsUrl="$TEKTON_DAHBOARD_URL" \
          --checkName="OWASP Dependency Check" \
          --checkConclusion="$(cat $(steps.step-odc-check.exitCode.path))"
      env:
        - name: GH_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: appId
        - name: GH_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: privateKey
        - name: GH_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: installId
