# Source: tektonpipelines/templates/tasks/secrets-scan.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secrets-scanner
  annotations:
    tekton.dev/pipelines.minVersion: "0.20.0"
    tekton.dev/tags: security
    tekton.dev/displayName: "secrets-scan"
spec:
  description: "run gitleaks scan. see https://github.com/zricethezav/gitleaks"
  workspaces:
    - name: source
  params:
    - name: JX_BOOT
    - name: BP_BUILDER_IMAGE
    - name: PULL_NUMBER
      description: PULL Request ID
    - name: SS_CONFIG_FILE
      description: "path to gitleaks config file"
      default: "gitleaks.toml"
    - name: PULL_BASE_SHA
      description: PULL_BASE_SHA
    - name: PULL_PULL_SHA
      description: last SHA
    - name: GITLEAKS_IMAGE
      default: "zricethezav/gitleaks:v8.6.1"
  results:
    - name: ss_status
      description: scan status
  stepTemplate:
    name: ""
    env:
      - name: SS_REPORT_PATH
        value: ".secrets-scan.sarif"
  steps:
    - name: ss-scan
      image: $(params.GITLEAKS_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        if gitleaks detect -s "$(workspaces.source.path)" -f sarif  -c "$(params.SS_CONFIG_FILE)" -r "$SS_REPORT_PATH" --redact  --log-opts="$(params.PULL_BASE_SHA)..$(params.PULL_PULL_SHA)" ; then
            echo "no leaks found"
            echo "0" > $(results.ss_status.path)
          else
            echo "1" > $(results.ss_status.path)
        fi
    - name: ss-publish-report
      image: $(params.BP_BUILDER_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        source $(workspaces.source.path)/.jx/variables.sh
        
        if [ "$(cat $(results.ss_status.path))" == "0" ]; then
          export CHECK_CONCLUSION="success"
        else
          export CHECK_CONCLUSION="failure"
        fi
        
        sdlcpipelinehelper sarif-publish \
          --repoOwner="$(params.REPO_OWNER)"  --repoName="$(params.REPO_NAME)" --sourceRoot="$(workspaces.source.path)" --commit="$HEAD_COMMIT" \
          --detailsUrl="$TEKTON_DAHBOARD_URL" \
          --checkName="GitLeaks" \
          --checkConclusion="$CHECK_CONCLUSION"
        
        rm $SS_REPORT_PATH
        
        if [ "$(cat $(results.ss_status.path))" == "1" ]; then
          echo "GitLeaks found some issues. pls check github check results"
          exit 1
        else
          echo "no issues found by GitLeaks"
        fi
      env:
        - name: GH_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: appId
        - name: GH_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: privateKey
        - name: GH_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: installId
