apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-build
spec:
  params:
    - name: NODE_VERSION
      default: "node:14-slim"
  workspaces:
    - name: source
      description: sources dir
  stepTemplate:
    name: ""
    env:
      - name: NPM_CONFIG_USERCONFIG
        value: /tekton/home/npm/.npmrc
      - name: HOME
        value: /tekton/home
    envFrom:
      - secretRef:
          name: jx-boot-job-env-vars
          optional: true
  steps:
    - image: ghcr.io/jenkins-x/jx-boot:3.2.235
      name: jx-variables
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        jx gitops variables
        jx gitops pr variables
    - image: $(params.NODE_VERSION)
      name: build-npm-install
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm ci
    - image: $(params.NODE_VERSION)
      name: build-npm-test
      script: |
        #!/bin/sh
        CI=true DISPLAY=:99 npm test
    - image: ghcr.io/jenkins-x/jx-registry:0.1.1
      name: check-registry
