apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-build
spec:
  params:
    - name: NODE_VERSION
      default: "node:14-slim"
    - name: "SDLC_PIPE_HELPER"
  workspaces:
    - name: source
      description: sources dir
  stepTemplate:
    name: ""
    volumeMounts:
      - mountPath: /tekton/home/npm
        name: npmrc
    env:
      - name: NPM_CONFIG_USERCONFIG
        value: /tekton/home/npm/.npmrc
      - name: HOME
        value: /tekton/home
    envFrom:
      - secretRef:
          name: jx-boot-job-env-vars
          optional: true
  volumes:
    - name: npmrc
      secret:
        optional: true
        secretName: npmrc
  steps:
    - image: $(params.NODE_VERSION)
      name: npm-ci-lint
      onError: continue
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm ci
        CI=true DISPLAY=:99 npm run lint
    - image: $(params.NODE_VERSION)
      name: npm-ci-test
      onError: continue
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        CI=true DISPLAY=:99 npm test
    - name: npm-test-publish-report
      image: "$(params.SDLC_PIPE_HELPER)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        if [[ -n "$PULL_PULL_SHA" ]]; then
          export COMMIT="$PULL_PULL_SHA"
        else
          export COMMIT="$PULL_BASE_SHA"
        fi
        
        sdlcpipelinehelper junit-report-publish \
          --checkName="npm test" \
          --repoOwner="$(params.REPO_OWNER)"  --repoName="$(params.REPO_NAME)" \
          --reportPaths="junit.xml" --commit="$COMMIT"
        
        sdlcpipelinehelper junit-report-publish \
                --checkName="eslint" \
                --repoOwner="$(params.REPO_OWNER)"  --repoName="$(params.REPO_NAME)" \
                --reportPaths="eslint.xml" --commit="$COMMIT"
      env:
        - name: GH_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: appId
        - name: GH_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: privateKey
        - name: GH_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: github-sdlc-app
              key: installId
